### PR TITLE
Some fixes for jeos-firstboot-snapshot

### PR DESCRIPTION
**Pull request by Vogtinator**
Make it ready for MicroOS and fix two other minor issues.

### CODE REVIEW

**Comment by lnussel** [comment]
would ConditionPathIsMountPoint in the service file do the job inside the service file instead of the shell script?

**Comment by Vogtinator** [comment]
> would ConditionPathIsMountPoint in the service file do the job inside the service file instead of the shell script?

Then we'd need yet another unit just to remove `/var/lib/YaST/reconfig_system`

**Comment by lnussel** [comment]
Indeed. OTOH that would make it more clear as removing the file wouldn't be a side effect. anyway, go ahead :)

**Review by gmoro — APPROVED** [review]
Looks good to me

**Pull request merged**
